@startuml
class Solution41 {
    Read and sort name list methods
    ..
    +List<String> createListofNames()
    +List<String> sortNames()
    --
    Output and run methods
    ..
    +String listOutput()
    +{static} void main()
}
note right of Solution41::createListofNames()
    Contains FileReader to
    exercise41_input.txt
end note
note right of Solution41::main
    Contains FileWriter to
    exercise41_output.txt
end note

@enduml